"""Driver identity: one source, read from a generated file.

Replaces two hand-maintained lists that had drifted apart - `calibrate.py`'s
driver_id -> (code, name) map, which covered 22 of 30 drivers and let the other
479 messages render as "NICHUL01", and `speaker.py`'s flat set of first names,
which had the mirror gap so the vocative cue never fired for six drivers.

`roster.json` is generated by `backend/data/build_roster.py` from FastF1 and
committed, so nothing here needs FastF1 or the network.
"""

from __future__ import annotations

import functools
import json
import os
import re

ROSTER_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "roster.json")


@functools.lru_cache(maxsize=1)
def _roster() -> dict[str, dict]:
    if not os.path.exists(ROSTER_PATH):
        return {}
    return json.load(open(ROSTER_PATH, encoding="utf-8"))["drivers"]


def display(driver_id: str) -> tuple[str, str]:
    """(code, full name) for a dataset driver_id.

    The fallback is deliberately visible rather than plausible. The old one
    returned `driver_id[:3]`, which produced "NIC" for Hulkenberg and "GUA" for
    Zhou - wrong codes that look like right ones, on 23.5% of the corpus.
    """
    d = _roster().get(driver_id)
    if d is None:
        return driver_id[:3], driver_id
    return d["code"], d["full_name"]


def known(driver_id: str) -> bool:
    return driver_id in _roster()


def all_ids() -> list[str]:
    return sorted(_roster())


@functools.lru_cache(maxsize=1)
def vocatives() -> dict[str, str]:
    """Every name an engineer might use on air -> the driver_id it belongs to.

    Includes surnames and radio nicknames ("checo", "danny ric", "hulk"), which
    the old first-names-only set missed entirely.
    """
    out: dict[str, str] = {}
    for did, d in _roster().items():
        for name in d.get("vocatives", []):
            out[name] = did
    return out


@functools.lru_cache(maxsize=1)
def _vocative_pattern() -> re.Pattern | None:
    """One alternation over every vocative, longest first.

    Longest-first matters: without it "danny" matches inside "danny ric" and the
    two-word form never wins.
    """
    names = sorted(vocatives(), key=len, reverse=True)
    if not names:
        return None
    return re.compile(r"\b(" + "|".join(re.escape(n) for n in names) + r")\b")


def find_vocatives(text: str) -> list[tuple[str, str]]:
    """Every driver name mentioned in `text`, as (name, driver_id) pairs."""
    pat = _vocative_pattern()
    if pat is None or not text:
        return []
    seen, out = set(), []
    for m in pat.finditer(text.lower()):
        name = m.group(1)
        if name not in seen:
            seen.add(name)
            out.append((name, vocatives()[name]))
    return out
